[build]
  base = "frontend"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://timis.onrender.com/api/v1"
  NEXT_PUBLIC_GRAPHQL_URL = "https://timis.onrender.com/graphql"
  NEXT_PUBLIC_WS_URL = "wss://timis.onrender.com/ws"

[[plugins]]
  package = "@netlify/plugin-nextjs"
